# Generated by Django 4.2.1 on 2023-10-02 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_alter_users_age_alter_users_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='address',
        ),
    ]
