# Generated by Django 4.2.1 on 2023-10-25 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0007_bloods'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bloods',
            old_name='byname',
            new_name='byuser',
        ),
    ]
